"""rename column

Revision ID: 5b24ea381a51
Revises: 0deb9614e846
Create Date: 2025-11-08 17:01:52.382796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b24ea381a51'
down_revision: Union[str, Sequence[str], None] = '0deb9614e846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('credibility_score', sa.Integer(), nullable=True))
    op.drop_column('analysis', 'creadibility_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('creadibility_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'credibility_score')
    # ### end Alembic commands ###
